name: Engine python package
on:
  push:
    tags:
      - "bamboo-engine-v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.0
        with:
          python_version: "3.11"
          poetry_version: "==2.0.0"
          ignore_dev_requirements: "yes"
          repository_name: "bamboo-engine"
          pypi_token: ${{ secrets.ENGINE_PYPI_TOKEN }}
