name: PR check

on:
  pull_request:
    branches: [master, develop, python_upgrade_master]

jobs:
  engine-lint:
    uses: TencentBlueKing/bamboo-engine/.github/workflows/engine_flake8_and_black.yml@python_upgrade_master

  pipeline-lint:
    uses: TencentBlueKing/bamboo-engine/.github/workflows/runtime_pipeline_flake8_and_black.yml@python_upgrade_master

  engine-unittest:
    needs: engine-lint
    uses: TencentBlueKing/bamboo-engine/.github/workflows/engine_unittest.yml@python_upgrade_master

  pipeline-unittest:
    needs: pipeline-lint
    uses: TencentBlueKing/bamboo-engine/.github/workflows/runtime_pipeline_unittest.yml@python_upgrade_master
  
  runtime-pipeline-intergration-test:
    needs: [engine-unittest, pipeline-unittest]
    uses: TencentBlueKing/bamboo-engine/.github/workflows/runtime_pipeline_end_to_end_test.yml@python_upgrade_master
  
  pipeline-intergration-test:
    needs: pipeline-unittest
    uses: TencentBlueKing/bamboo-engine/.github/workflows/pipeline_end_to_end_test.yml@python_upgrade_master
