name: Runtime Pipeline python package
on:
  push:
    tags:
      - "bamboo-pipeline-v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.10

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 2.0.0

      - name: Remove Test Code
        run: |
          cd runtime/bamboo-pipeline
          rm -rf pipeline/django_signal_valve/tests
          rm -rf pipeline/tests
          rm -rf pipeline/contrib/external_plugins/tests
          poetry build -vvv
          poetry config pypi-token.pypi ${{ secrets.PIPELINE_PYPI_TOKEN }}
          poetry publish
